package com.example.demo.advancePlusOne;

import org.springframework.ai.chat.model.ChatResponse;
import org.springframework.ai.chat.prompt.Prompt;
import reactor.core.publisher.Mono;

public interface LlmProvider {

    /**
     * Executes a chat completion call against the underlying AI engine using Spring AI.
     *
     * @param prompt The fully optimized, structured Prompt containing System, User, and Assistant messages.
     * @return The rich ChatResponse generated by the model containing usage metrics and the generated text.
     */
    Mono<ChatResponse> askAi(Prompt prompt);

    /**
     * Identifies which provider implementation this strategy belongs to (e.g., "GEMINI", "FAST_TIER").
     */
    String getProviderName();
}