package com.example.demo.advancePlusOne;

import reactor.core.publisher.Mono;

public interface LlmProvider {

    /**
     * Executes a chat completion call against the underlying AI engine.
     *
     * @param compiledPrompt The fully optimized, stitched context payload.
     * @return The text response generated by the model.
     */
    Mono<String> askAi(String compiledPrompt);

    /**
     * Identifies which provider implementation this strategy belongs to (e.g., "GEMINI", "CLAUDE").
     */
    String getProviderName();
}
